name: 'deploy'
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --force
      - name: Build
        run: npm run build --prod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/